{
 "title": "Acompanhamento suporte",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Temperatura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select value from machines_data md\nwhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time)\norder by time asc\n"
    }
   ]
  },
  {
   "title": "Temperatura do servidor",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\nfrom machines_data\nwhere sensor_type = '02' and machine_id = '1' and $__timeFilter(time)\norder by time desc"
    },
    {
     "rawSql": "SELECT \"time\" AS \"time\", value as \"Predicted value\" --, upper_confidence, lower_confidence\r\nFROM metrics\r\n--inner join sensors\r\n--on metrics.sensor_id = sensors.id \r\nWHERE time BETWEEN TO_TIMESTAMP(${__from:date:seconds}+1800) AND TO_TIMESTAMP(${__to:date:seconds}) AND sensor_id = 1"
    }
   ]
  },
  { "title": "Estatísticas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Temperatura do servidor",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\nfrom machines_data\nwhere sensor_type = '02' and machine_id = '1' and $__timeFilter(time)\norder by time desc"
    }
   ]
  },
  {
   "title": "Temperatura máxima no período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max(value) from machines_data md\nwhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Desvio padrão da amostra no período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select cast(stddev_samp(value) as dec(14,2)) stddevsamp\n from machines_data md\nwhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Temperatura média no período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(value) from machines_data md\nwhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time)\n"
    }
   ]
  },
  {
   "title": "Amplitude no período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (max(value) - min(value)) as amplitude from machines_data md\nwhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time)\n\n\n\n"
    }
   ]
  },
  {
   "title": "Mediana no período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MAX(value) as \"Median of value\"\nFROM\n  (\n    SELECT\n      value,\n      ntile(2) OVER (ORDER BY value) AS bucket\n    FROM\n      machines_data where machine_id = 1 and sensor_type = '02' and $__timeFilter(time)\n  ) as t\nWHERE bucket = 1  \nGROUP BY bucket;"
    }
   ]
  },
  {
   "title": "Cp (LSE - LIE) = 5 º ---- > (20 - 25)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select 5/(6* cast(stddev_samp(value) as dec(14,2))) stddevsamp\n from machines_data md\nwhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Cpk esquerda - Valor de CPK é min LSI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n\t((select avg(value) from machines_data md\r\n\twhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time) ) - 20)\r\n\t/\r\n\t(select 3* cast(stddev_samp(value) as dec(14,2)) stddevsamp\r\n \tfrom machines_data md\r\n\twhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time) )\r\n\tfrom machines_data md where machine_id = 1 and sensor_type = '02' and $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "Cpk direita - Valor de CPK é min LSE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n\t(25-(select avg(value) from machines_data md\r\n\twhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time) ))\r\n\t/\r\n\t(select 3* cast(stddev_samp(value) as dec(14,2)) stddevsamp\r\n \tfrom machines_data md\r\n\twhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time) )\r\n\tfrom machines_data md where machine_id = 1 and sensor_type = '02' and $__timeFilter(time)"
    }
   ]
  },
  {
   "title": "6 * Desvio padrão da amostra no período - 6 Sigma",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 7, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select 6* cast(stddev_samp(value) as dec(14,2)) stddevsamp\n from machines_data md\nwhere machine_id = 1 and sensor_type = '02' and $__timeFilter(time) "
    }
   ]
  }
 ]
}