{
 "title": "Timeline (12h)",
 "tags": [
  "lt",
  "man",
  "prod"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "maquina",
    "label": "Máquina",
    "query": "select distinct (description) from machines"
   }
  ]
 },
 "panels": [
  { "title": "Informações gerais", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '2d' AND NOW()\r\norder by time desc\r\nlimit 1\r\n"
    }
   ]
  },
  {
   "title": "Contagem de peles",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) as \"contagem\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina'\r\nand mada.sensor_type = '01'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('5','4') and $__timeFilter(time) and ms.duration <60\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and $__timeFilter(time) and ms.duration <60\r\ngroup by machine_id) as AllTime from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Distribuição dos status no tempo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nsum(ms.duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('5') and $__timeFilter(time) \r\ngroup by machine_id) as \"Trabalhando com OP\",\r\n(select\r\nsum(ms.duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('4') and $__timeFilter(time) \r\ngroup by machine_id) as \"Trabalhando sem OP\",\r\n(select\r\nsum(ms.duration)   \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('3') and $__timeFilter(time) \r\ngroup by machine_id) as \"Máquina parada\",\r\n(select\r\nsum(ms.duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('2') and $__timeFilter(time) \r\ngroup by machine_id) as \"Máquina ociosa\",\r\n(select\r\nsum(ms.duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('1','0') and $__timeFilter(time) \r\ngroup by machine_id) as \"Desligada\",\r\n(select \r\nsum(ms.duration)\r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and $__timeFilter(time) \r\ngroup by machine_id) as \"Tempo total\" from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Linha do tempo da máquina: $maquina",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select time, mast.state as \"Estado\"\r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere $__timeFilter(time) and mach.description = '$maquina' \r\n--where mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '7d' AND NOW()\r\norder by time desc\r\n"
    },
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"QTD de peles\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.description = '${maquina}' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\nand $__timeFilter(time)\r\nGROUP by 1\r\nORDER BY time desc"
    },
    {
     "rawSql": "select time,\r\nextra_data ->> 'nrOp' as \"OP\",\r\nextra_data ->> 'nmCliente' as \"Cliente\",\r\nextra_data ->> 'artigo' as \"Artigo\",\r\nextra_data ->> 'nmEventoParada' as \"Paradas\"\r\nfrom machines_data md \r\ninner join machines mach on md.machine_id = mach.id\r\nwhere $__timeFilter(time) and mach.description = '$maquina'\r\norder by time asc\r\n\r\n/*select mast.time,\r\nmada.extra_data ->> 'nrOp' as \"OP\",\r\nmada.extra_data ->> 'nmCliente' as \"Cliente\",\r\nmada.extra_data ->> 'artigo' as \"Artigo\",\r\nmada.extra_data ->> 'nmEventoParada' as \"Paradas\"\r\nfrom machines_state mast\r\ninner join machines_data mada on mada.machine_id = mast.machine_id\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere $__timeFilter(mast.time) and mach.description = '$maquina' \r\norder by mast.time desc*/"
    }
   ]
  },
  { "title": "Hora-hora", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Hora/Hora contagem de peles",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '10m'), \r\n  sum(mada.value) as \"Quantidade por hora\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.description = '${maquina}' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\nand $__timeFilter(time)\r\nGROUP by 1\r\nORDER BY time desc"
    }
   ]
  },
  { "title": "Tabela Hora - Hora", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Tabela hora - hora",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "   SELECT\r\n    peles.hour ,\r\n    \"QTD de peles\",\r\n    UpTime,\r\n    Ocioso,\r\n    Parada,\r\n    Desligada\r\nFROM\r\n(\r\n    SELECT\r\n        date_trunc('hour', time) as hour,\r\n        SUM(value) as \"QTD de peles\"\r\n    FROM\r\n        machines_data\r\n    WHERE\r\n        sensor_type = '01' AND machine_id = 1\r\n    GROUP BY\r\n        hour\r\n) as peles\r\nLEFT JOIN\r\n(\r\n    SELECT\r\n        date_trunc('hour', time) as hour,\r\n        SUM(CASE WHEN state in ('5','4') THEN duration ELSE 0 END) / SUM(duration) as UpTime\r\n    FROM\r\n        machines_state\r\n    WHERE\r\n        machine_id = 1 AND duration < 60\r\n    GROUP BY\r\n        hour\r\n) as uptime\r\nON peles.hour = uptime.hour\r\nLEFT JOIN\r\n(\r\n    SELECT\r\n        date_trunc('hour', time) as hour,\r\n        SUM(CASE WHEN state in ('0','1') THEN duration ELSE 0 END) / SUM(duration) as Desligada\r\n    FROM\r\n        machines_state\r\n    WHERE\r\n        machine_id = 1 AND duration < 60\r\n    GROUP BY\r\n        hour\r\n) as desligada\r\nON peles.hour = desligada.hour\r\nLEFT JOIN\r\n(\r\n    SELECT\r\n        date_trunc('hour', time) as hour,\r\n        SUM(CASE WHEN state = '2' THEN duration ELSE 0 END) / SUM(duration) as Ocioso\r\n    FROM\r\n        machines_state\r\n    WHERE\r\n        machine_id = 1 AND duration < 60\r\n    GROUP BY\r\n        hour\r\n) as ocioso\r\nON peles.hour = ocioso.hour\r\nLEFT JOIN\r\n(\r\n    SELECT\r\n        date_trunc('hour', time) as hour,\r\n        SUM(CASE WHEN state = '3' THEN duration ELSE 0 END) / SUM(duration) as Parada\r\n    FROM\r\n        machines_state\r\n    WHERE\r\n        machine_id = 1 AND duration < 60\r\n    GROUP BY\r\n        hour\r\n) as parada\r\nON peles.hour = parada.hour\r\nORDER BY\r\n    hour desc\r\n   --limit 13;"
    }
   ]
  },
  { "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 } }
 ]
}