{
 "title": "Buffing machine",
 "tags": [ "prod" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "maquina",
    "label": "Machine",
    "query": "select distinct (description) from machines where id in ('11') order by description "
   }
  ]
 },
 "panels": [
  { "title": "-", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  { "title": "Production information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '20 seconds' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Last 12 hours hide count",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"Quantidade por hora\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.description = '${maquina}' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\n-- $__timeFilter(\"time\") and \r\nGROUP by 1\r\nORDER BY time asc\r\nlimit 13"
    }
   ]
  },
  {
   "title": "P.O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nrOp' as \"Número da ordem de produção\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc\r\n"
    }
   ]
  },
  {
   "title": "Article",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*SELECT time, extra_data ->> 'artigo' as \"Artigo\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '10 minutes' AND NOW()\r\norder by time asc*/\r\n\r\n/*SELECT time, extra_data ->> 'artigo' as \"Artigo\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '10 minutes' AND NOW()\r\norder by time asc*/\r\n\r\nSELECT extra_data ->> 'artigo' as \"Artigo\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time asc\r\nlimit 1"
    }
   ]
  },
  {
   "title": "Hide count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) as \"Contagem de peles\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina'\r\nand mada.sensor_type = '01'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Client",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nmCliente' as \"Cliente\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Current stop event",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'nmEventoParada' as \"Descrição Evento Parada\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '24 s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('5','4') and $__timeFilter(time) and duration < 60\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and $__timeFilter(time) and duration < 60\r\ngroup by machine_id) as AllTime from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Final thickness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'espessuraFinal' as \"Espessura Final\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Color",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'cor' as \"Cor\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Status time distribution",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('5') and $__timeFilter(time) and ms.duration <30\r\ngroup by machine_id) as \"Running with P.O\",\r\n(select\r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('4') and $__timeFilter(time) and ms.duration <30\r\ngroup by machine_id) as \"Running without P.O\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('3') and $__timeFilter(time) and ms.duration <31\r\ngroup by machine_id) as \"Stopped machine\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('2') and $__timeFilter(time) and ms.duration <31\r\ngroup by machine_id) as \"Idle machine\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('1','0') and $__timeFilter(time) and ms.duration <31\r\ngroup by machine_id) as \"Offline\",\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and $__timeFilter(time) and ms.duration <31\r\ngroup by machine_id) as \"Total time\" from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Timeline of: $maquina",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere $__timeFilter(time) and mach.description = '$maquina'  \r\n--where mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '7d' AND NOW()\r\norder by time desc\r\n"
    },
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"Hide count\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.description = '$maquina' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\nand $__timeFilter(time)\r\nGROUP by 1\r\nORDER BY time desc"
    },
    {
     "rawSql": "select time,\r\nextra_data ->> 'nrOp' as \"P.O\",\r\nextra_data ->> 'cor' as \"Color\",\r\nextra_data ->> 'nmEventoParada' as \"Stop\"\r\nfrom machines_data md \r\ninner join machines mach on md.machine_id = mach.id\r\nwhere $__timeFilter(time) and mach.description = '$maquina' \r\norder by time asc\r\n\r\n/*select mast.time,\r\nmada.extra_data ->> 'nrOp' as \"OP\",\r\nmada.extra_data ->> 'nmCliente' as \"Cliente\",\r\nmada.extra_data ->> 'artigo' as \"Artigo\",\r\nmada.extra_data ->> 'nmEventoParada' as \"Paradas\"\r\nfrom machines_state mast\r\ninner join machines_data mada on mada.machine_id = mast.machine_id\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere $__timeFilter(mast.time) and mach.description = '$maquina' \r\norder by mast.time desc*/"
    }
   ]
  },
  { "title": "Speed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Speed (m/min)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, value as \"qtdTinta\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina'\r\nand mada.sensor_type = '09'  -- and time between now() - INTERVAL '1 m' AND NOW() \r\nand $__timeFilter(time)\r\nlimit 1\r\n--GROUP BY mada.time , mada.value"
    }
   ]
  },
  {
   "title": "Speed in time (m/min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Speed\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina'\r\nand mada.sensor_type = '09' --and sensor_id = 60\r\nand $__timeFilter(time)\r\norder by time desc\r\n--GROUP BY mada.time , mada.value"
    }
   ]
  },
  { "title": "Electric power consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Amount of electric power consumption",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 34 }
  },
  {
   "title": "Electric power consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"kWh\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '16' and  mach.description = '$maquina' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\nand $__timeFilter(\"time\")\r\nGROUP by 1\r\nORDER BY time desc\r\nlimit 13"
    }
   ]
  },
  {
   "title": "Amount of cost of electrical consumption",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 42 }
  },
  {
   "title": "Cost of electrical consumption",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value)* 0.677 as \"Cost per hour\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '16' and mach.description = '$maquina'\r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\nand $__timeFilter(\"time\")\r\nGROUP by 1\r\nORDER BY time desc\r\nlimit 13"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "<center><img style=\"height:3.5rem\" src = \"https://i.imgur.com/oCn2qFx.png\">\n</center>"
   }
  }
 ]
}