{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1>Welcome to virtual tannery</h1>\n<center><img style=\"height:5rem\" src = \"https://i.imgur.com/juDnDFB.png\">\n</center>\n"
   }
  },
  {
   "title": "REWET DRUM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'REWET DRUM'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "SAMMYING MACHINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere time between now() - interval '20s' and now() and mach.description = 'SAMMYING MACHINE'\r\norder by mast.time asc\r\n"
    }
   ]
  },
  {
   "title": "SPLITTING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'SPLITTING'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "SHAVING MACHINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'SHAVING MACHINE'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "RETANNING DRUM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'RETANNING DRUM'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "SETTING OUT MACHINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'SETTING OUT MACHINE'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "VACCUM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'VACCUM'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "TOGGLING",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'TOGGLING'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "BUFFING MACHINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'BUFFING MACHINE'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "ROLLER COAT MACHINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'ROLLER COAT MACHINE'\norder by mast.time asc\n\n"
    }
   ]
  },
  {
   "title": "SPRAY MACHINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'SPRAY MACHINE'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "CONTINUE EMBOSSING MACHINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'CONTINUE EMBOSSING MACHINE'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "MILLING DRUM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'MILLING DRUM'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "MEANSURING MACHINE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'MEANSURING MACHINE'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "-",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  description , id from machines where id = 1"
    }
   ]
  },
  {
   "title": "-",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  description , id from machines where id = 1"
    }
   ]
  },
  {
   "title": "Status distribution",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(mach.id) as \"Machines\"\r\n\tfrom machines mach WHERE id <15"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Running with PO\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('5')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Running without PO\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('4')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Idle machine\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('2')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Stopped machine\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('3')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Offline\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('0','1')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    }
   ]
  }
 ]
}