{
 "title": "Vaccum",
 "tags": [ "prod" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "-", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  { "title": "Production information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere mach.id = '3' and \"time\" BETWEEN NOW() - INTERVAL '20 seconds' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Last 12 hours hide count",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"Quantidade por hora\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.id = '3' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\n-- $__timeFilter(\"time\") and \r\nGROUP by 1\r\nORDER BY time asc\r\nlimit 13"
    }
   ]
  },
  {
   "title": "Curent P.O",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nrOp' as \"Número da ordem de produção\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc\r\n"
    }
   ]
  },
  {
   "title": "Color",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'cor' as \"Cor\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Hide count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) as \"Contagem de peles\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3'\r\nand mada.sensor_type = '01'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Client",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nmCliente' as \"Cliente\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Article",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*SELECT time, extra_data ->> 'artigo' as \"Artigo\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '10 minutes' AND NOW()\r\norder by time asc*/\r\n\r\n/*SELECT time, extra_data ->> 'artigo' as \"Artigo\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '${maquina}' and \"time\" BETWEEN NOW() - INTERVAL '10 minutes' AND NOW()\r\norder by time asc*/\r\n\r\nSELECT extra_data ->> 'artigo' as \"Artigo\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time asc\r\nlimit 1"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 3 and state in ('5','4') and $__timeFilter(time) and duration < 60\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 3 and $__timeFilter(time) and duration < 60\r\ngroup by machine_id) as AllTime from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Final thickness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'espessuraFinal' as \"Espessura Final\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Stop event",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'nmEventoParada' as \"Descrição Evento Parada\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and \"time\" BETWEEN NOW() - INTERVAL '24 s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": " Status distribution in time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = '3' and state in ('5') and $__timeFilter(time) and ms.duration <30\r\ngroup by machine_id) as \"Running with P.O\",\r\n(select\r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = '3' and state in ('4') and $__timeFilter(time) and ms.duration <30\r\ngroup by machine_id) as \"Running without P.O\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = '3' and state in ('3') and $__timeFilter(time) and ms.duration <31\r\ngroup by machine_id) as \"Stopped machine\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = '3' and state in ('2') and $__timeFilter(time) and ms.duration <31\r\ngroup by machine_id) as \"Idle machine\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = '3' and state in ('1','0') and $__timeFilter(time) and ms.duration <31\r\ngroup by machine_id) as \"Offline\",\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = '3' and $__timeFilter(time) and ms.duration <31\r\ngroup by machine_id) as \"Total time\" from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  { "title": "Timeline of: Vácuo MecMan", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 } },
  { "title": "Vaccum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Set time vaccum table 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and sensor_id = 91 and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Set time vaccum table 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and sensor_id = 91 and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Set time vaccum table 3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and sensor_id = 93 and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Set time vaccum table 4",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and sensor_id = 94 and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Vaccum",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "rawSql": "select time, (value) as \"Vácuo\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3'\r\nand mada.sensor_type = '06' and sensor_id < 90\r\nand $__timeFilter(time)\r\norder by time desc"
    }
   ]
  },
  {
   "title": " Vacuum histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": " Vacuum histogram",
     "type": "histogram",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "pressurembar" } },
     "targets": [
      {
       "rawSql": "select time, value as \"Vácuo\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and mada.value between 100 and 500 \r\nand mada.sensor_type = '06' and sensor_id < 90\r\nand $__timeFilter(time)\r\norder by time desc"
      }
     ]
    },
    {
     "title": "Pressure peak in range",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select max(value) from machines_data mada\r\nwhere machine_id = 3 and mada.value between 100 and 500\r\nand sensor_type = '06'  and $__timeFilter(time)\r\n\r\n"
      }
     ]
    },
    {
     "title": "Average pressure over the interval",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select avg(value) from machines_data mada\r\nwhere machine_id = 3 and mada.value between 100 and 500\r\nand sensor_type = '06' and $__timeFilter(time)\r\n"
      }
     ]
    },
    {
     "title": "Amplitude in range",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (max(value) - min(value)) as amplitude from machines_data mada\r\nwhere machine_id = 3 and sensor_type = '06' and mada.value between 100 and 500 and $__timeFilter(time)\r\n\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Sample standard deviation",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select cast(stddev_samp(value) as dec(14,2)) stddevsamp\r\n from machines_data mada\r\nwhere machine_id = 3 and mada.value between 100 and 500\r\nand sensor_type = '06' and $__timeFilter(time)\r\n\r\n"
      }
     ]
    },
    {
     "title": "Cp - Maximum variation of 500mbar",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 49 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select 500/(6* cast(stddev_samp(value) as dec(14,2))) stddevsamp\r\n from machines_data mada\r\nwhere machine_id = 3 and sensor_type = '06'  and mada.value between 100 and 500\r\nand $__timeFilter(time) "
      }
     ]
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Set temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, value\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and sensor_id = 95 and \"time\" BETWEEN NOW() - INTERVAL '240 s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3'\r\nand mada.sensor_type = '02' and sensor_id != 95\r\nand $__timeFilter(time)\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Temperature histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature histogram",
     "type": "histogram",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "select time, value as \"Temperatura\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = '3' and mada.value > 25\r\nand mada.sensor_type = '02' and sensor_id != 95\r\nand $__timeFilter(time)\r\norder by time desc"
      }
     ]
    },
    {
     "title": "Maximum temperature reached in the period",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select max(value) from machines_data md\r\nwhere machine_id = 3 and sensor_type = '02' and $__timeFilter(time)\r\n\r\n"
      }
     ]
    },
    {
     "title": "Average temperature reached in the period",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select avg(value) from machines_data md\r\nwhere machine_id = 3 and sensor_type = '02' and $__timeFilter(time)\r\n"
      }
     ]
    },
    {
     "title": "Amplitude in the period",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select (max(value) - min(value)) as amplitude from machines_data md\r\nwhere machine_id = 3 and sensor_type = '02' and $__timeFilter(time)\r\n\r\n\r\n\r\n"
      }
     ]
    },
    {
     "title": "Standard deviation of the sample in the period",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select cast(stddev_samp(value) as dec(14,2)) stddevsamp\r\n from machines_data md\r\nwhere machine_id = 3 and sensor_type = '02' and $__timeFilter(time)\r\n\r\n"
      }
     ]
    },
    {
     "title": "Cp - Max. variation of 2 degrees",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "select 2/(6* cast(stddev_samp(value) as dec(14,2))) stddevsamp\r\n from machines_data md\r\nwhere machine_id = 3 and sensor_type = '02' and $__timeFilter(time) "
      }
     ]
    }
   ]
  },
  { "title": "Electric power consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Amount of electric power consumption",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) as \"Contagem de peles\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = 3\r\nand mada.sensor_type = '16'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Electric power consumption",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"Hourly consumption\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '16' and mach.id = '3' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\nand $__timeFilter(\"time\")\r\nGROUP by 1\r\nORDER BY time desc\r\nlimit 13"
    }
   ]
  },
  {
   "title": "Amount of cost of electrical consumption",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) * 0.677 as \"Contagem de peles\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.id = 3\r\nand mada.sensor_type = '16'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Cost of electrical consumption",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value)* 0.677 as \"Cost per hour\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '16' and mach.id = '3' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\nand $__timeFilter(\"time\")\r\nGROUP by 1\r\nORDER BY time desc\r\nlimit 13"
    }
   ]
  }
 ]
}