{
 "title": "Home",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "\n<center><img style=\"height:5rem\" src = \"https://i.imgur.com/juDnDFB.png\">\n</center>\n"
   }
  },
  {
   "title": "REBAJADAS FLAMAR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'REBAJADAS FLAMAR'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "REBAJADAS MATRIX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'REBAJADAS MATRIX'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "MÁQ. ESCURRIR MVC4S VERSUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'MÁQ. ESCURRIR MVC4S VERSUS'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "MÁQ. DE DESCARNAR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'MÁQ. DE DESCARNAR'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "MÁQ. DE DIVIDIR TRIPA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere time between now() - interval '20s' and now() and mach.description = 'MÁQ. DE DIVIDIR TRIPA'\r\norder by mast.time asc\r\n"
    }
   ]
  },
  {
   "title": "MÁQ. ESCURRIR WET BLUE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'MÁQ. ESCURRIR WET BLUE'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "EXTENDIDO DYNAVAC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'EXTENDIDO DYNAVAC'\norder by mast.time asc\n\n"
    }
   ]
  },
  {
   "title": "SECADO A VACIO MANUAL 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'SECADO A VACIO MANUAL 1'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "SECADO A VACIO MANUAL 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'SECADO A VACIO MANUAL 2'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "SECADO A VACIO MANUAL 3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'SECADO A VACIO MANUAL 3'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "SECADO A VACIO MANUAL 4",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'SECADO A VACIO MANUAL 4'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "MÁQ. CEPILLAR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'MÁQ. CEPILLAR'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "ABLANDAR ACABADOS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'ABLANDAR ACABADOS'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "VACIO DYNAVAC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'VACIO DYNAVAC'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "QUICK1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'QUICK1'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "MÁQ. ABLANDADORA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'MÁQ. ABLANDADORA'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "ESMERILADO FLAMAR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'ESMERILADO FLAMAR'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "STARPLUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'STARPLUS'\norder by mast.time asc\n\n"
    }
   ]
  },
  {
   "title": "CABINA BARNINI 3B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere time between now() - interval '20s' and now() and mach.description = 'CABINA BARNINI 3B'\r\norder by mast.time asc\r\n\r\n"
    }
   ]
  },
  {
   "title": "KELA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'KELA'\norder by mast.time asc\n"
    }
   ]
  },
  {
   "title": "QUICK2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'QUICK2'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "ESMERILADAS BUMA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'ESMERILADAS BUMA'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "TOPSTAR",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere time between now() - interval '20s' and now() and mach.description = 'TOPSTAR'\r\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "CABINA BARNINI 3A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'CABINA BARNINI 3A'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "MÁQUINA MEDIR WEGA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'MÁQUINA MEDIR WEGA'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "GEMATA ROTOPLUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'GEMATA ROTOPLUS'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "PRENSA MOSTARDINI",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'PRENSA MOSTARDINI'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "NUBUK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'NUBUK'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "CABINA BARNINI 2B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'CABINA BARNINI 2B'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "CABINA BARNINI 2A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'CABINA BARNINI 2A'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "UNKNOWN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'UNKNOWN'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "CABINA BARNINI 1A",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'CABINA BARNINI 1A'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "CABINA BARNINI 1B",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  mast.state from machines_state mast\ninner join machines mach on mach.id = mast.machine_id \nwhere time between now() - interval '20s' and now() and mach.description = 'CABINA BARNINI 1B'\norder by mast.time asc"
    }
   ]
  },
  {
   "title": "Status distribution",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(mach.id) as \"Machines\"\r\n\tfrom machines mach"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Running with PO\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('5')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Running without PO\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('4')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Idle machine\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('2')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Stopped machine\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('3')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    },
    {
     "rawSql": "select count(distinct mach.id) as \"Offline\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere state in ('0','1')\r\nand mast.\"time\" between now() - interval '30s' and now()"
    }
   ]
  }
 ]
}