{
 "title": "Toggling Zona 4",
 "tags": [
  "m2",
  "man"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status atual da máquina",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mada\r\non mada.id = mast.machine_id\r\nwhere mada.id = '2' and \"time\" BETWEEN NOW() - INTERVAL '2d' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Temperatura Atual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select md.value as \"Temperatura zona 3\"\nfrom machines_data md\nwhere md.sensor_id ='16' and md.machine_id = '2'\nand md.time between now() - INTERVAL '1 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "title": "Temperatura Zona 4",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Zona 4\"\nfrom machines_data md\nwhere machine_id = '2' and sensor_id = '16' \nand $__timeFilter(time) \norder by time asc"
    }
   ]
  },
  {
   "title": "Total de quadros",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select mada.time, sum(mada.value) as \"contagem\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_id = '22' and MACHINE_ID = '2'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Temp. Média Período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Temperatura média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_id = '16' and machine_id = '02'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Status ventilador 1",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mada.value\r\nfrom machines_data mada\r\ninner join machines mach\r\non machine_id = id\r\nwhere sensor_id = '47' and mada.machine_id ='2' \r\nand \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Temp. Máxima Período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Temperatura média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_id = '16' and machine_id = '02'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Status ventilador 2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mada.value\r\nfrom machines_data mada\r\ninner join machines mach\r\non machine_id = id\r\nwhere sensor_id = '48' and mada.machine_id ='2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Status ventilador 3",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mada.value\r\nfrom machines_data mada\r\ninner join machines mach\r\non machine_id = id\r\nwhere sensor_id = '49' and mada.machine_id ='2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Umidade Atual",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Umidade zona 1\"\nfrom machines_data md\nwhere md.sensor_id ='20' and md.machine_id = '2'\nand md.time between now() - INTERVAL '1 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "title": "Umidade Zona 4",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Zona 4\"\nfrom machines_data md\nwhere machine_id = '2' and sensor_id = '20'  \nand $__timeFilter(time) \norder by time asc"
    }
   ]
  },
  {
   "title": "Status ventilador 4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mada.value\r\nfrom machines_data mada\r\ninner join machines mach\r\non machine_id = id\r\nwhere sensor_id = '50' and mada.machine_id ='2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Status Válvula Vapor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mada.value\r\nfrom machines_data mada\r\ninner join machines mach\r\non machine_id = id\r\nwhere sensor_id = '34' and mada.machine_id ='2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Umidade Média Período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Temperatura média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_id = '20' and machine_id = '02'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Status Válvula Dumper",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "/*select time, mada.value\r\nfrom machines_data mada\r\ninner join machines mach\r\non machine_id = id\r\nwhere sensor_type = '16' and mada.machine_id ='2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc*/"
    }
   ]
  },
  {
   "title": "Umidade Máxima Período",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"umidade máxima\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_id = '20' and machine_id = '02'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value\r\norder by time asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 13, "x": 5, "y": 20 },
   "options": {
    "content": "<center><img style=\"height:3.5rem\" src = \"https://i.imgur.com/oCn2qFx.png\">\n</center>\n"
   }
  }
 ]
}