{
 "title": "Linha do tempo",
 "tags": [
  "lt",
  "man",
  "prod"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "maquina",
    "query": "select distinct (description) from machines"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '2d' AND NOW()\r\norder by time desc\r\n"
    }
   ]
  },
  {
   "title": "Linha do tempo de $maquina",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '7d' AND NOW()\r\norder by time desc"
    },
    {
     "rawSql": "select time,\r\nextra_data ->> 'nrOp' as \"OP\",\r\nextra_data ->> 'nmCliente' as \"Cliente\",\r\nextra_data ->> 'artigo' as \"Artigo\",\r\nextra_data ->> 'nmEventoParada' as \"Paradas\"\r\nfrom machines_data md \r\ninner join machines mach on md.machine_id = mach.id\r\nwhere $__timeFilter(time) and mach.description = '$maquina'\r\norder by time asc"
    }
   ]
  },
  { "title": "Informações complementares", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Contagem de quadros",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) as \"contagem\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere sensor_id = '22' and mach.description = '$maquina'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere mach.description = '$maquina' and state in ('5') and $__timeFilter(time)\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere mach.description = '$maquina' and $__timeFilter(time)\r\ngroup by machine_id) as AllTime from machines_state ms2 "
    }
   ]
  },
  {
   "title": "Contagem de quadros por hora (últimas 12 horas)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"Quantidade por hora\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_id = '22' and mach.description = '$maquina' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\n-- $__timeFilter(\"time\") and \r\nGROUP by 1\r\nORDER BY time asc\r\nlimit 13\r\n"
    }
   ]
  },
  {
   "title": "Espessura final",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'espessuraFinal' as \"Espessura final\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Número do pedido atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nrPedido' as \"Número do pedido\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Cor atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'cor' as \"Cor\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "options": {
    "content": "<center><img style=\"height:3.5rem\" src = \"https://i.imgur.com/oCn2qFx.png\">\n</center>"
   }
  }
 ]
}