{
 "title": "Toggling - Parâmetros",
 "tags": [
  "m2",
  "man"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status Atual da Máquina",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mada\r\non mada.id = mast.machine_id\r\nwhere mada.id = '2' and \"time\" BETWEEN NOW() - INTERVAL '2d' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Total de Quadros",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select mada.time, sum(mada.value) as \"contagem\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_id = '22' and MACHINE_ID = '2'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Evento Parada Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'nmEventoParada' as \"Descrição Evento Parada\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Cliente Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'nmCliente' as \"Cliente\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Nº O.P Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'nrOp' as \"Nº OP\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Nº Pedido Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'nrPedido' as \"Nº Pedido\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  { "title": "Temperatura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Temp. Atual Zona 1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Zona 1\"\nfrom machines_data md\nwhere md.sensor_id ='13' and md.machine_id = '2' \nand md.time between now() - INTERVAL '1 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "title": "Temp. Atual Zona 2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Zona 2\"\nfrom machines_data md\nwhere md.sensor_id ='14' and md.machine_id = '2' \nand md.time between now() - INTERVAL '1 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Zona 1\"\nfrom machines_data md\nwhere machine_id = '2' and sensor_id = '13' \nand $__timeFilter(time) \norder by time asc"
    },
    {
     "rawSql": "select time, value as \"Zona 2\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '14'\nand $__timeFilter(time) \norder by time asc"
    },
    {
     "rawSql": "select time, value as \"Zona 3\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '15'\nand $__timeFilter(time) \norder by time asc"
    },
    {
     "rawSql": "select time, value as \"Zona 4\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '16'\nand $__timeFilter(time) \norder by time asc"
    }
   ]
  },
  {
   "title": "Temp. Atual Zona 3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Zona 3\"\nfrom machines_data md\nwhere md.sensor_id ='15' and md.machine_id = '2'\nand md.time between now() - INTERVAL '1 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "title": "Temp. Atual Zona 4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Zona 4\"\nfrom machines_data md\nwhere md.sensor_id ='16' and md.machine_id = '2' \nand md.time between now() - INTERVAL '1 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  { "title": "Umidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Umidade Atual Zona 1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Zona 1\"\nfrom machines_data md\nwhere md.sensor_id ='17' and md.machine_id = '2' and md.time between now() - INTERVAL '10 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "title": "Umidade Atual Zona 2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Zona 1\"\nfrom machines_data md\nwhere md.sensor_id ='18' and md.machine_id = '2' and md.time between now() - INTERVAL '10 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "title": "Umidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Zona 1\"\nfrom machines_data md\nwhere machine_id = '2' and sensor_id = '17' \nand $__timeFilter(time)  \norder by time asc"
    },
    {
     "rawSql": "select time, value as \"Zona 2\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '18' \nand $__timeFilter(time) \norder by time asc"
    },
    {
     "rawSql": "select time, value as \"Zona 3\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '19'\nand $__timeFilter(time) \norder by time asc"
    },
    {
     "rawSql": "select time, value as \"Zona 4\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '20'\nand $__timeFilter(time) \norder by time asc"
    }
   ]
  },
  {
   "title": "Umidade Atual Zona 3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Zona 1\"\nfrom machines_data md\nwhere md.sensor_id ='19' and md.machine_id = '2' and md.time between now() - INTERVAL '10 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "title": "Umidade Atual Zona 4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select  md.value as \"Zona 1\"\nfrom machines_data md\nwhere md.sensor_id ='20' and md.machine_id = '2' and md.time between now() - INTERVAL '10 m' AND NOW() \norder by md.time asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<center><img style=\"height:3.5rem\" src = \"https://i.imgur.com/oCn2qFx.png\">\n</center>"
   }
  }
 ]
}