{
 "title": "Toggling - Processo",
 "tags": [
  "m2",
  "prod"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Análise de produção", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mada\r\non mada.id = mast.machine_id\r\nwhere mada.id = '2' and \"time\" BETWEEN NOW() - INTERVAL '2d' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Nome da Operação",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nmOperacao' as \"Nome da operação\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Status da Toggling no Tempo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "rawSql": "select time, cast(state as int) \r\nfrom machines_state ms \r\nwhere machine_id ='2' and time between now() - interval '30 days' and now()\r\norder by time ASC"
    }
   ]
  },
  {
   "title": "Nº O.P Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nrOp' as \"Número da ordem de produção\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc\r\n"
    }
   ]
  },
  {
   "title": "Artigo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'artigo' as \"Artigo\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Contagem de Quadros ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) as \"contagem\"\r\nfrom machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere sensor_id = '22' and machine_id = '2'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Cor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'cor' as \"Cor\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "UpTime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms \r\nwhere machine_id = '2' and state in ('5') and $__timeFilter(time)\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\nwhere machine_id = '2' and $__timeFilter(time)\r\ngroup by machine_id) as AllTime from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Contagem de Quadros por Hora (últimas 12)",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"Quantidade por hora\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_id = '22' and mada.machine_id = '2' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\n-- $__timeFilter(\"time\") and \r\nGROUP by 1\r\nORDER BY time asc\r\nlimit 13"
    }
   ]
  },
  {
   "title": "Cliente",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nmCliente' as \"Cliente\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Distribuição do tempo nos estados",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration)  \r\nfrom machines_state ms \r\nwhere machine_id = '2' and state in ('5') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina operando com OP\",\r\n(select\r\nSUM (duration) \r\nfrom machines_state ms \r\nwhere machine_id = '2' and state in ('4') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina operando sem OP\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\nwhere machine_id = '2' and state in ('3') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina parada\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\nwhere machine_id = '2' and state in ('2') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina ociosa\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\nwhere machine_id = '2' and state in ('1','0') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina desligada\",\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\nwhere machine_id = '2' and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Tempo total transcorrido\" from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Espessura Final",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'espessuraFinal' as \"Espessura Final\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Evento Parada Atual",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'nmEventoParada' as \"Descrição Evento Parada\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere machine_id = '2' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<center><img style=\"height:3.5rem\" src = \"https://i.imgur.com/oCn2qFx.png\">\n</center>"
   }
  },
  { "title": "Histórico de paradas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Últimos eventos parada apontadas ",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select time, current -> 'nmEventoParada' as \"Parada\"\nfrom machines_event \nwhere current -> 'nmEventoParada' notnull and current -> 'nmEventoParada' != '\"null\"' and \"time\" BETWEEN NOW() - INTERVAL '30d' AND NOW()\norder by time desc"
    }
   ]
  },
  {
   "title": "Quantidade de paradas por classificação de paradas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT current -> 'nmEventoParada' as \"paradas\" ,\r\ncount (current -> 'nmEventoParada')\r\nFROM machines_event me \r\nwhere current -> 'nmEventoParada' notnull and current -> 'nmEventoParada' != '\"null\"'\r\ngroup by me.\"current\" \r\norder by count(current -> 'nmEventoParada')\r\nlimit 10"
    }
   ]
  }
 ]
}