{
 "title": "Alarmes",
 "tags": [ "alarmes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM machines_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Umidade",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM machines_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperatura máquina 1 alarme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_type = '02' and machine_id = '1'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value \r\norder by machines_data.time desc"
    }
   ]
  },
  {
   "title": "Umidade máquina 1 alarme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_type = '03' and machine_id = '1'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value \r\norder by machines_data.time desc"
    }
   ]
  },
  {
   "title": "Temperatura máquina 2 alarme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_type = '02' and machine_id = '2'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value \r\norder by machines_data.time desc"
    }
   ]
  },
  {
   "title": "Umidade máquina 2 alarme",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 9 },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_type = '03' and machine_id = '2'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value \r\norder by machines_data.time desc"
    }
   ]
  }
 ]
}