{
 "title": "Parâmetros de máquina",
 "tags": [ "man" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "maquina",
    "label": "máquina",
    "query": "select distinct description  from machines m \ninner join machines_data md \non id = machine_id"
   }
  ]
 },
 "panels": [
  { "title": "Análise de máquina", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://www.systemhaus.com.br/site/visual/img/logo-rodape.png?v=2_1\">\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM machines_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Status atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '2d' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Temperatura média",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Temperatura média\" \r\nfrom machines_data mada\r\ninner join machines mach \r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '02' and mach.description in ('$maquina')\r\nand $__timeFilter(time) \r\ngroup by  mada.time,mada.value "
    }
   ]
  },
  {
   "title": "Temperatura da máquina $maquina",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '02' and mach.description in ('$maquina')\r\nand $__timeFilter(time) \r\ngroup by  mada.time, mada.value \r\norder by mada.time desc"
    }
   ]
  },
  {
   "title": "Ordem de produção atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nrOp' as \"Número da ordem de produção\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc\r\n"
    }
   ]
  },
  {
   "title": "Total de peles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) as \"contagem\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description = '$maquina'\r\nand mada.sensor_type = '01'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Umidade média",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Umidade média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_type = '03' and description in ('$maquina')\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value "
    }
   ]
  },
  {
   "title": "Umidade da máquina $maquina",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Temperatura média\" \r\nfrom machines_data mada\r\ninner join machines mach \r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '03' and mach.description in ('$maquina')\r\nand $__timeFilter(time) \r\ngroup by  mada.time,mada.value "
    }
   ]
  },
  {
   "title": "Contagem de peles nas últimas 12 horas",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"Quantidade por hora\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.description = '${maquina}' \r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\n-- $__timeFilter(\"time\") and \r\nGROUP by 1\r\nORDER BY time asc\r\nlimit 13"
    }
   ]
  },
  {
   "title": "Power On",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 16, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('5','4') and $__timeFilter(time)\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and $__timeFilter(time)\r\ngroup by machine_id) as AllTime from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  { "title": "Limites", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Ultrapassou os limites de especificação (últimos 30 dias)",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select maev.time as \"Data/Hora\",\r\n  mach.description as \"Máquina\",\r\n\tmaev.type \"Tipo\",\r\n\tmaev.current -> 'value' as \"Valor medido\",\r\n\tmaev.previous -> 'upper_limit' as \"Limite superior\",\r\n\tmaev.previous -> 'lower_limit' as \"Limite inferior\" \r\nfrom machines_event maev\r\ninner join machines mach\r\non mach.id = maev.machine_id\r\nwhere maev.type in ('passou_limite_superior','passou_limite_inferior') and mach.description = '${maquina}'  and time between now() - interval '30 days' and now()"
    }
   ]
  },
  {
   "title": "Quantidade de vezes limites ultrapassados (últimos 30 dias)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\t(select count(type)\r\n\tfrom machines_event maev\r\n\tinner join machines mach\r\n\ton mach.id = maev.machine_id\r\n\twhere maev.type in ('passou_limite_inferior') and mach.description = '${maquina}' and time between now() - interval '30 days' and now()\r\n\tgroup by maev.type\r\n\torder by maev.type) as \"Passou limite inferior\",\r\n\t(select count(type)\r\nfrom machines_event maev\r\ninner join machines mach\r\non mach.id = maev.machine_id\r\nwhere maev.type in ('passou_limite_superior') and mach.description = '${maquina}' and time between now() - interval '30 days' and now()\r\ngroup by maev.type\r\norder by maev.type)\tas \"Passou limite superior\"\r\nfrom machines_event me\r\n\tlimit 1"
    }
   ]
  }
 ]
}