{
 "title": "Análise de parâmetros",
 "tags": [ "MR" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "maquina",
    "label": "máquina",
    "query": "select distinct description  from machines m \ninner join machines_data md \non id = machine_id"
   }
  ]
 },
 "panels": [
  { "title": "Análise de máquina", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status atual",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mada.value\r\nfrom machines_data mada\r\ninner join machines mach\r\non machine_id = id\r\nwhere sensor_type = '04' and mach.description in ('$maquina')\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Power On",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time_bucket_gapfill('1 minute', time) as time\r\n, count(locf(max(md.value))) over (order by 1) as \"Total\"\r\n, sum(locf(max(md.value))) over (order by 1) as \"Trabalhado\"\r\nfrom machines_data md\r\nwhere sensor_type = '04'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Ordem de produção atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'Número da ordem de produção' as \"Número da ordem de produção\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mach.description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc\r\n"
    }
   ]
  },
  {
   "title": "Total de peles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select mada.time, sum(mada.value) as \"contagem\"\r\nfrom machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.description in ('$maquina')\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Temperatura média",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Temperatura média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_type = '02' and description in ('$maquina')\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value "
    }
   ]
  },
  {
   "title": "Temperatura da máquina $maquina",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Temperatura\"\r\n\r\nfrom machines_data \r\n\r\ninner join machines m \r\non machine_id = id\r\n\r\nwhere sensor_type = '02'   and description in ('$maquina')\r\n\r\nand $__timeFilter(time) \r\n\r\ngroup by  machines_data.time, value \r\norder by machines_data.time desc"
    }
   ]
  },
  {
   "title": "Umidade média",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Umidade média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_type = '03' and description in ('$maquina')\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value "
    }
   ]
  },
  {
   "title": "Umidade da máquina $maquina",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select time, value as \"Umidade\" \r\n\r\nfrom machines_data \r\n\r\ninner join machines m \r\non machine_id = id\r\n\r\nwhere sensor_type = '03' and description in ('$maquina')\r\n\r\nand $__timeFilter(time) \r\n\r\ngroup by  machines_data.time, value "
    }
   ]
  },
  {
   "title": "Contagem de peles nas últimas 12 horas",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(mada.time, '1h'), \r\n  sum(value) as \"Quantidade por hora\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '24 HOURS' AND NOW()\r\n-- $__timeFilter(\"time\") and \r\nGROUP by 1 \r\n\r\nORDER BY time desc\r\n\r\nlimit 12"
    }
   ]
  },
  { "title": "Alertas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Painel de alertas",
   "type": "alertlist",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM machines_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "options": {
    "content": "<img src=\"https://www.systemhaus.com.br/site/visual/img/logo-rodape.png?v=2_1\">\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM machines_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}