{
 "title": "Análise de processo",
 "tags": [ "MR" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "maquina",
    "label": "máquina",
    "query": "select distinct description  from machines m \ninner join machines_data md \non id = machine_id"
   }
  ]
 },
 "panels": [
  { "title": "Análise de produção", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status atual",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mada.value\r\nfrom machines_data mada\r\ninner join machines mach\r\non machine_id = id\r\nwhere sensor_type = '04' and mach.description in ('$maquina') -- and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Ordem de produção atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'Número da ordem de produção' as \"Número da ordem de produção\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc\r\n"
    }
   ]
  },
  {
   "title": "UP Time da máquina $maquina",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time_bucket_gapfill('1 minute', time) as time\r\n, count(locf(max(md.value))) over (order by 1) as \"Total\"\r\n, sum(locf(max(md.value))) over (order by 1) as \"Trabalhado\"\r\nfrom machines_data md\r\nwhere sensor_type = '04'\r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Total de peles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select time, sum(value) as \"contagem\"\r\nfrom machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere sensor_type = '01' and description in ('$maquina') \r\nand $__timeFilter(time)\r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Contagem de peles nas últimas 6 horas",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(value) as \"Quantidade por hora\" \r\nFROM machines_data \r\ninner join machines m\r\non machine_id = id\r\nwhere sensor_type = '01' and description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '24 HOURS' AND NOW()\r\n-- $__timeFilter(\"time\") and \r\nGROUP by 1 \r\nORDER BY time desc\r\nlimit 6"
    }
   ]
  },
  {
   "title": "Cor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'Cor' as \"Cor\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Espessura Final",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'Espessura Final' as \"Espessura Final\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Artigo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'Artigo' as \"Artigo\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Cliente",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'Cliente' as \"Cliente\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Código do produto",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'Código do produto' as \"Código do produto\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Nome da Operação",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'Nome da operação' as \"Nome da operação\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere description in ('$maquina') and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "options": {
    "content": "<img src=\"https://www.systemhaus.com.br/site/visual/img/logo-rodape.png?v=2_1\">\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  value\nFROM machines_data\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}