{
 "title": "Linha do tempo Toggling",
 "tags": [
  "lt",
  "man",
  "prod",
  "m2"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status atual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere mach.id = 2 and \"time\" BETWEEN NOW() - INTERVAL '2d' AND NOW()\r\norder by time desc\r\nlimit 1\r\n"
    }
   ]
  },
  {
   "title": "Linha do tempo do Toggling",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 22, "x": 2, "y": 1 },
   "targets": [
    {
     "rawSql": "select time, mast.state as \"Status\"\r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere $__timeFilter(time) and mach.id = 2\r\norder by time desc"
    },
    {
     "rawSql": "select time,\r\nextra_data ->> 'artigo' as \"Artigo\",\r\nextra_data ->> 'espessuraFinal' as \"Espessura\",\r\nextra_data ->> 'nmEventoParada' as \"Paradas\"\r\nfrom machines_data md \r\ninner join machines mach on md.machine_id = mach.id\r\nwhere $__timeFilter(time) and mach.id = 2\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 2 and state in ('5','4') and $__timeFilter(time)\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 2 and $__timeFilter(time)\r\ngroup by machine_id) as AllTime from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 2 and state in ('5') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina operando com OP\",\r\n(select\r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 2 and state in ('4') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina operando sem OP\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 2  and state in ('3') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina parada\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 2 and state in ('2') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina ociosa\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 2 and state in ('1','0') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina desligada\",\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 2 and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Tempo total transcorrido\" from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Parâmetros de máquinas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperatura",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "select time, value as \"Zona 1\"\nfrom machines_data md\nwhere machine_id = '2' and sensor_id = '13' \nand $__timeFilter(time) \norder by time asc"
      },
      {
       "rawSql": "select time, value as \"Zona 2\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '14'\nand $__timeFilter(time) \norder by time asc"
      },
      {
       "rawSql": "select time, value as \"Zona 3\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '15'\nand $__timeFilter(time) \norder by time asc"
      },
      {
       "rawSql": "select time, value as \"Zona 4\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '16'\nand $__timeFilter(time) \norder by time asc"
      }
     ]
    },
    {
     "title": "Umidade",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "select time, value as \"Zona 1\"\nfrom machines_data md\nwhere machine_id = '2' and sensor_id = '17' \nand $__timeFilter(time)  \norder by time asc"
      },
      {
       "rawSql": "select time, value as \"Zona 2\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '18' \nand $__timeFilter(time) \norder by time asc"
      },
      {
       "rawSql": "select time, value as \"Zona 3\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '19'\nand $__timeFilter(time) \norder by time asc"
      },
      {
       "rawSql": "select time, value as \"Zona 4\"\nfrom machines_data\nwhere machine_id = '2' and sensor_id = '20'\nand $__timeFilter(time) \norder by time asc"
      }
     ]
    }
   ]
  },
  { "title": "Contagem de peles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Contagem de Quadros por Hora (últimas 12)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  $__timeGroup(time, '1h'), \r\n  sum(mada.value) as \"Quantidade por hora\" \r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere mada.sensor_type = '01' and mach.id = 2 and mada.value < 200\r\nand \"time\" BETWEEN NOW() - INTERVAL '12 HOURS' AND NOW()\r\n-- $__timeFilter(\"time\") and \r\nGROUP by 1\r\nORDER BY time asc\r\nlimit 13"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<center><img style=\"height:3.5rem\" src = \"https://i.imgur.com/oCn2qFx.png\">\n</center>"
   }
  }
 ]
}