{
 "title": "System Performance",
 "tags": [ "info" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka services",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"kafka-broker-1:29101|kafka-broker-2:29101|kafka-broker-3:29101|zookeeper-instance-1:29101|zookeeper-instance-2:29101|zookeeper-instance-3:29101\"}"
    }
   ]
  },
  {
   "title": "Solution services",
   "type": "stat",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"postgresql-exporter:9187|data-analyzer:8000|machine-learning-controller:8000|alert-dispatcher:8000|localhost:9090\"}"
    }
   ]
  },
  {
   "title": "Data Analyzer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Events Processed per Second",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(data_analyzer_processed_events_total[$__rate_interval])"
      }
     ]
    },
    {
     "title": "State Monitoring Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "state_manager_monitoring_time_sum{}/state_manager_monitoring_time_count{}"
      }
     ]
    }
   ]
  },
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "People login",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(grafana_api_user_signup_completed_total{instance=\"grafana:3000\"})"
    }
   ]
  },
  {
   "title": "Events Processed per Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(grafana_api_dashboard_get_milliseconds)"
    }
   ]
  }
 ]
}