{
 "title": "Home v.2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display:flex; justify-content: space-around;\">\n<center><img style=\"height:5rem\" src = \"https://i.imgur.com/juDnDFB.png\">\n</center>\n\n<center><img src = \"https://www.pelesminuano.com.br/img/logo-minuano-curtume.svg\">\n</center>\n\n\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 0, "y": 3 },
   "options": {
    "content": "<h1><center> Curtume </center></h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 3 },
   "options": {
    "content": "<h1><center>Secagem</center></h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
   "options": {
    "content": "<h1><center> Acabamento </center></h1>"
   }
  },
  {
   "title": "Uptime Geral",
   "type": "stat",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere  state in ('5','4') and mach.department  = 'Secagem' and $__timeFilter(time) ) as \"UpTimeSecagem\" , -- and ms.\"time\" between now() - interval '1h' and now()) as \"UpTimeSecagem\",\r\n(select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere  state in ('5') and mach.department  = 'Acabamento' and $__timeFilter(time) ) as \"UpTimeAcabamento\",  -- and ms.\"time\" between now() - interval '1h' and now()) as \"UpTimeAcabamento\",\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere $__timeFilter(time)) as AllTime --  ms.\"time\" between now() - interval '1h' and now()) as AllTime -- from machines_state ms2 "
    }
   ]
  },
  {
   "title": "Uptime Secagem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere mach.department  = 'Secagem' and state in ('5','4') and $__timeFilter(time) --  and ms.\"time\" between now() - interval '1h' and now()\r\ngroup by mach.department) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere mach.department  = 'Secagem' and $__timeFilter(time) --and ms.\"time\" between now() - interval '1h' and now() --and $__timeFilter(time)\r\ngroup by mach.department) as AllTime -- from machines_state ms2 "
    }
   ]
  },
  {
   "title": "Uptime Acabamento últimos 60 min.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere mach.department  = 'Acabamento' and state in ('5') and $__timeFilter(time) -- and ms.\"time\" between now() - interval '1h' and now()\r\ngroup by mach.department) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere mach.department  = 'Acabamento' and $__timeFilter(time) -- and ms.\"time\" between now() - interval '1h' and now()\r\ngroup by mach.department) as AllTime -- from machines_state ms2 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(mach.id) as \"Máquinas\"\r\n\tfrom machines mach"
    },
    {
     "rawSql": "select count(distinct mast.machine_id) as \"Ligadas com OP\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mast.state in ('5')\r\nand mast.\"time\" between now() - interval '1m' and now()"
    },
    {
     "rawSql": "select count(distinct mast.machine_id) as \"Ligadas sem OP\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mast.state in ('4') and machine_id = 2\r\nand mast.\"time\" between now() - interval '25s' and now()"
    },
    {
     "rawSql": "select count(distinct mast.machine_id) as \"Ociosas\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mast.state in ('2') and (mast.state = '4' and machine_id = 2)\r\nand mast.\"time\" between now() - interval '25s' and now()"
    },
    {
     "rawSql": "select count(distinct mast.machine_id) as \"Paradas\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mast.state in ('3')\r\nand mast.\"time\" between now() - interval '25s' and now()"
    },
    {
     "rawSql": "select count(distinct mast.machine_id) as \"Desligadas\"\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mast.state in ('0','1')\r\nand mast.\"time\" between now() - interval '25s' and now()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select count(mach.id) \r\n\tfrom machines mach \r\n\twhere mach.department = 'Secagem') as \"Máquinas\",\r\n(select count(distinct mach.id)\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mach.department = 'Secagem'\r\nand mast.state in ('5') \r\nand mast.\"time\" between now() - interval '20s' and now()) as \"Ligadas com OP\",\r\n(select count(distinct mach.id)\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mach.department = 'Secagem'\r\nand mast.state in ('4') \r\nand mast.\"time\" between now() - interval '20s' and now()) as \"Ligadas sem OP\",\r\n(select count(distinct mach.id) \r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mach.department = 'Secagem'\r\nand mast.state in ('2')\r\nand mast.\"time\" between now() - interval '20s' and now()) as \"Ociosas\",\r\n(select count(distinct mach.id) \r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mach.department = 'Secagem'\r\nand mast.state in ('3')\r\nand mast.\"time\" between now() - interval '20s' and now()) as \"Paradas\",\r\n(select count(distinct mach.id) \r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mach.department = 'Secagem'\r\nand mast.state in ('0','1')\r\nand mast.\"time\" between now() - interval '20s' and now()) as \"Desligadas\"\r\nfrom machines_state ms \r\ngroup by 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select count(mach.id) \r\n\tfrom machines mach \r\n\twhere mach.department = 'Acabamento') as \"Máquinas\",\r\n(select count(distinct mach.id)\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mach.department = 'Acabamento'\r\nand mast.state in ('5') \r\nand mast.\"time\" between now() - interval '20s' and now()) as \"Ligadas com OP\",\r\n(select count(distinct mach.id)\r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mach.department = 'Acabamento'\r\nand mast.state in ('4') \r\nand mast.\"time\" between now() - interval '20s' and now()) as \"Ociosas\",\r\n(select count(distinct mach.id) \r\nfrom machines_state mast\r\ninner join machines mach on mach.id = mast.machine_id \r\nwhere mach.department = 'Acabamento'\r\nand mast.state in ('0','1')\r\nand mast.\"time\" between now() - interval '20s' and now()) as \"Desligadas\"\r\nfrom machines_state ms \r\ngroup by 1"
    }
   ]
  }
 ]
}