{
 "title": "Prensa Rotativa",
 "tags": [
  "m1",
  "prod"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status Atual da Máquina",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mada\r\non mada.id = mast.machine_id\r\nwhere mada.id = '1' and \"time\" BETWEEN NOW() - INTERVAL '60s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Temperatura do rolo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select time , value as \"Temperatura\" from machines_data\nwhere machine_id ='1' and sensor_id = '8' \nand $__timeFilter(time) \norder by time asc"
    }
   ]
  },
  {
   "title": "Temperatura Média",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Temperatura média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_id = '8' and machine_id = '1'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value "
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere mach.id = '1' and state in ('5') and $__timeFilter(time)\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach on ms.machine_id = mach.id \r\nwhere mach.id = '1' and $__timeFilter(time)\r\ngroup by machine_id) as AllTime from machines_state ms2 where $__timeFilter(time) "
    }
   ]
  },
  {
   "title": "Nº O.P Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nrOp' as \"Nº Ordem de Produção\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '1' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Velocidade (m/min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select time , value as \"Velocidade\" from machines_data\nwhere machine_id ='1' and sensor_id = '11'\nand $__timeFilter(time) \norder by time asc"
    }
   ]
  },
  {
   "title": "Velocidade Média (m/min)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Temperatura média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_id = '11' and machine_id = '1'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value "
    }
   ]
  },
  {
   "title": "Artigo Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'artigo' as \"Artigo\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '1' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Cliente Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, extra_data ->> 'nmCliente' as \"Cliente\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '1' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Pressão",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "select time , value as \"Pressão\" from machines_data\nwhere machine_id ='1' and sensor_id = '6'\nand $__timeFilter(time) \norder by time asc"
    }
   ]
  },
  {
   "title": "Pressão Média",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select time, avg(value) as \"Pressão média\" \r\nfrom machines_data \r\ninner join machines m \r\non machine_id = id\r\nwhere sensor_type = '06' and machine_id = '1'\r\nand $__timeFilter(time) \r\ngroup by  machines_data.time, value "
    }
   ]
  },
  {
   "title": "Cor Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "  SELECT time, extra_data ->> 'cor' as \"Cor\"\r\nFROM machines_data\r\ninner join machines m\r\non machine_id = id\r\nwhere machine_id = '1' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time desc"
    }
   ]
  },
  {
   "title": "Evento Parada Atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT mada.time, mada.extra_data ->> 'nmEventoParada' as \"Descrição Evento Parada\"\r\nFROM machines_data mada\r\ninner join machines mach\r\non mada.machine_id = mach.id\r\nwhere machine_id = '1' and \"time\" BETWEEN NOW() - INTERVAL '65s' AND NOW()\r\norder by time asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<center><img style=\"height:3.5rem\" src = \"https://i.imgur.com/oCn2qFx.png\">\n</center>\n"
   }
  }
 ]
}