{
 "title": "Linha do tempo prensa rotativa",
 "tags": [
  "lt",
  "man",
  "prod",
  "m1"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Status atual",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select time, mast.state \r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere mach.id = 1 and \"time\" BETWEEN NOW() - INTERVAL '2d' AND NOW()\r\norder by time desc\r\nlimit 1\r\n"
    }
   ]
  },
  {
   "title": "Linha do tempo da prensa rotativa ",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "rawSql": "select time, mast.state as \"Status\"\r\nfrom machines_state mast\r\ninner join machines mach\r\non mach.id = mast.machine_id\r\nwhere $__timeFilter(time) and mach.id = '1'\r\norder by time desc"
    },
    {
     "rawSql": "select time,\r\nextra_data ->> 'nrOp' as \"OP\",\r\nextra_data ->> 'nmCliente' as \"Cliente\",\r\nextra_data ->> 'artigo' as \"Artigo\",\r\nextra_data ->> 'nmEventoParada' as \"Paradas\"\r\nfrom machines_data md \r\ninner join machines mach on md.machine_id = mach.id\r\nwhere $__timeFilter(time) and mach.id = 1\r\norder by time asc"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 1 and state in ('5') and $__timeFilter(time)\r\ngroup by machine_id) as UpTime,\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms\r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 1 and $__timeFilter(time)\r\ngroup by machine_id) as AllTime from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  { "title": "Informações complementares", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 1 and state in ('5') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina operando com OP\",\r\n(select\r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.id = 1 and state in ('4') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina ociosa\",\r\n(select\r\nSUM (duration)  \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and state in ('1','0') and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Máquina desligada\",\r\n(select \r\nSUM (duration) \r\nfrom machines_state ms \r\ninner join machines mach\r\non ms.machine_id = mach.id\r\nwhere mach.description = '$maquina' and $__timeFilter(time)\r\ngroup by machine_id)/60 as \"Tempo total transcorrido\" from machines_state ms2 \r\ngroup by 1"
    }
   ]
  },
  {
   "title": "Temperatura do rolo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select time , value as \"Temperatura\" from machines_data\r\nwhere machine_id ='1' and sensor_id = '8' \r\nand $__timeFilter(time) \r\norder by time asc"
    }
   ]
  },
  {
   "title": "Velocidade do rolo (m/min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select time , value as \"Temperatura\" from machines_data\r\nwhere machine_id ='1' and sensor_id = '11' \r\nand $__timeFilter(time) \r\norder by time asc"
    }
   ]
  },
  {
   "title": "Pressão",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "select time , value as \"Temperatura\" from machines_data\r\nwhere machine_id ='1' and sensor_id = '6' \r\nand $__timeFilter(time) \r\norder by time asc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "<center><img style=\"height:3.5rem\" src = \"https://i.imgur.com/oCn2qFx.png\">\n</center>"
   }
  }
 ]
}